import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en" className="h-full">
      <body className="min-h-screen h-full overflow-hidden"> {/* Ajout de overflow-hidden ici */}
      <div className="w-full h-full flex  relative">
          <ul className="bg-blue-500 h-full w-16">
              <li><Link href="/">Home</Link></li>
              <li><Link href="/articles">Articles</Link></li>
          </ul>
          <div className="grow flex-col">
              <div className="bg-emerald-300 h-14">
                  search
              </div>
              <div className="grow bg-red-600 h-full overflow-y-scroll p-4 pb-16"> {/* overflow-y-scroll est ici */}
                  {children}
              </div>
          </div>
      </div>
      </body>
      </html>
  );
}
